name: Release

on:
  push:
    tags:
      - '**'

jobs:
  create_pre_release:
    name: Create pre-release

    runs-on: ubuntu-latest

    steps:
      # The pre-release must be created only once, hence the split
      # into multiple jobs with different `strategy`.
      - name: Create a Github pre-release
        id: create_pre_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: true

      - name: Output `release_url` into a temporary file
        run: echo "${{ steps.create_pre_release.outputs.upload_url }}" > release_url.txt

      - name: Save the `release_url` temporary file
        uses: actions/upload-artifact@v1
        with:
          name: release_url
          path: release_url.txt

  release:
    name: Build and publish wheels

    needs: [create_pre_release]

    strategy:
      matrix:
        # The job runs on different OS.
        target: [
          # Linux, amd64
          { id: 'linux-amd64', os: 'ubuntu-latest', rust-target: 'x86_64-unknown-linux-gnu', rust-toolchain: 'stable' },
          # macOS, amd64
          { id: 'darwin-amd64', os: 'macos-latest', rust-target: 'x86_64-apple-darwin', rust-toolchain: 'stable' },
          # Windows, amd64
          { id: 'windows-amd64', os: 'windows-latest', rust-target: 'x86_64-pc-windows-msvc', rust-toolchain: 'stable' },
          # Windows, x86
          #{ id: 'windows-x86', os: 'windows-latest', rust-target: 'i686-pc-windows-msvc' },
          # Linux, aarch64
          { id: 'linux-aarch64', os: ['self-hosted', 'aarch64'], rust-target: 'aarch64-unknown-linux-gnu', rust-toolchain: 'nightly' },
        ]
        # The job runs on different Python versions.
        python: [3.5, 3.6, 3.7, 3.8, '3.9-beta.5']
      # As soon as one job fails in the matrix, all the other
      # in-progress jobs are canceled.
      fail-fast: true

    runs-on: ${{ matrix.target.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.target.rust-toolchain }}
          default: true
          override: true
          target: ${{ matrix.target.rust-target }}

      - name: Cache Cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ matrix.target.rust-target }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ matrix.target.rust-target }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ matrix.target.rust-target }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Python ${{ matrix.python }}
        if: matrix.target.id != 'linux-aarch64'
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Fake `pyenv` installation
        if: matrix.target.id != 'linux-aarch64'
        shell: bash
        run: |
          echo "${{ matrix.python }}" > .python-version

      - name: Cache Python version
        if: matrix.target.id == 'linux-aarch64'
        uses: actions/cache@v1
        with:
          path: ~/.pyenv/versions/
          key: ${{ matrix.target.rust-target }}-pyenv-version-${{ matrix.python }}

      - name: Set up Python ${{ matrix.python }}
        if: matrix.target.id == 'linux-aarch64'
        shell: bash
        run: |
          test -d $HOME/.pyenv || curl -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
          pyenv install --list | grep '^  ${{ matrix.python }}' | tail -n 1 | tr -d '[:space:]' > .python-version
          pyenv install --skip-existing "$(cat .python-version)"

      - name: Set up just
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/$(cat .python-version)/bin:$PATH"
          test -f $HOME/.cargo/bin/just || cargo install just

      - name: Prelude
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/$(cat .python-version)/bin:$PATH"
          just prelude

      - name: Build the wheel
        id: create_wheel
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/$(cat .python-version)/bin:$PATH"
          if test -d .env/bin/; then source .env/bin/activate; else source .env/Scripts/activate; fi
          maturin list-python
          PYTHON_INTERPRETER=$(maturin list-python | grep -o "CPython $(cat .python-version | grep -o -E '^[^\.]+\.[^\.]+').* at .*" | cut -d' ' -f 4 | tr '\\' '/')
          echo "Selected interpreter: ${PYTHON_INTERPRETER}"
          just build-wheel "${PYTHON_INTERPRETER}" "${{ matrix.target.rust-target }}"
          wheel=$(ls target/wheels/wasmer-*.whl | grep "cp$(cat .python-version | grep -o -E '^[^\.]+\.[^\.]+' | tr -d '.')" | tail -n1)
          echo ${wheel}
          echo ::set-output name=path::${wheel}
          echo ::set-output name=name::$(basename ${wheel})

      - name: Load the `release_url` from the temporary file
        uses: actions/download-artifact@v1
        with:
          name: release_url

      - name: Read the `release_url` temporary file
        id: get_release_info
        shell: bash
        run: |
          value=$(cat release_url/release_url.txt)
          echo ::set-output name=upload_url::$value

      - name: Upload the wheel as Github pre-release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ${{ steps.create_wheel.outputs.path }}
          asset_name: ${{ steps.create_wheel.outputs.name }}
          asset_content_type: application/x-pywheel+zip

      - name: Publish the wheel on Pypi
        if: matrix.target.id != 'linux-aarch64'
        shell: bash
        env:
          TWINE_PASSWORD: ${{ secrets.MATURIN_PASSWORD }}
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          export PATH="$HOME/.pyenv/versions/$(cat .python-version)/bin:$PATH"
          if test -d .env/bin/; then source .env/bin/activate; else source .env/Scripts/activate; fi
          just publish

  release-any:
    name: Release any wheels

    needs: [create_pre_release]

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          target: ${{ matrix.target.rust-target }}

      - name: Cache Cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo bin
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Set up just
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          test -f $HOME/.cargo/bin/just || cargo install just

      - name: Prelude
        shell: bash
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          just prelude

      - name: Build the wheel
        id: create_wheel
        shell: bash
        run: |
          if test -d .env/bin/; then source .env/bin/activate; else source .env/Scripts/activate; fi
          just build-any-wheel
          wheel=$(ls target/wheels/wasmer-*.whl)
          echo ${wheel}
          echo ::set-output name=path::${wheel}
          echo ::set-output name=name::$(basename ${wheel})

      - name: Load the `release_url` from the temporary file
        uses: actions/download-artifact@v1
        with:
          name: release_url

      - name: Read the `release_url` temporary file
        id: get_release_info
        shell: bash
        run: |
          value=$(cat release_url/release_url.txt)
          echo ::set-output name=upload_url::$value

      - name: Upload the wheel as Github pre-release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ${{ steps.create_wheel.outputs.path }}
          asset_name: ${{ steps.create_wheel.outputs.name }}
          asset_content_type: application/x-pywheel+zip

      - name: Publish the wheel on Pypi
        shell: bash
        env:
          TWINE_PASSWORD: ${{ secrets.MATURIN_PASSWORD }}
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          if test -d .env/bin/; then source .env/bin/activate; else source .env/Scripts/activate; fi
          just publish-any
